sudo: false
language: node_js
node_js:
- '8'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- npm install coveralls --save-dev
- npm i jest --save-dev
- npm i jest-cli -g
- npm update
install:
- npm install
script:
- jest --coverage && coveralls < coverage/lcov.info
